
public enum EVENT_PLAYER
{
    PLAYER_LEFT_MOVE,
    PLAYER_RIGHT_MOVE,
    PLAYER_UP_MOVE,
    PLAYER_DOWN_MOVE,
    PLAYER_MOVE_COMPLETE,
    PLAYER_ATTACK_COMPLETE,
    PLAYER_DIE_COMPLETE,
    PLAYER_GET_ITEM_COMPLETE,
    PLAYER_RING_SLOT_FULL,
    PLAYER_ITEM_UNEQUIP,
}

public enum EVENT_ABILITY_INVEN_UI
{
    OPEN_ABILITY_DETAIL_UI,
    USE_ABILITY,
    SET_ABILITY,
}

public enum EVENT_STATUS_POPUP_UI
{
    REQUEST_EQUIP_DATA,
    RESPONDED_EQUIP_DATA,
}

public enum EVENT_EQUIP_INVEN_UI
{
    OPEN_EQUIP_INVENTORY_DETAIL_UI,
    REQUEST_EQUIP_INVENTORY_DATA,
    RESPONDED_EQUIP_INVENTORY_DATA,
    ON_CLICK_READING_GLASS,
}

public enum EVENT_CONSUME_INVEN_UI
{
    OPEN_CONSUME_INVENTORY_DETAIL_UI,
    REQUEST_CONSUME_INVENTORY_DATA,
    RESPONDED_CONSUME_INVENTORY_DATA,
    ON_CLICK_READING_GLASS,
}

public enum EVENT_ITEM_POPUP_UI
{
    REQUEST_READING_GLASS_DATA,
    RESPONDED_READING_GLASS_DATA,
    ON_CLICK_DISMISS,
    ON_CLICK_APPLY,
}

public enum EVENT_BOTTOM_BASE_UI
{
    ON_CLICK_STATUS_BUTTON,
    ON_CLICK_DIR_BUTTON,
    ON_CLICK_CONSUME_BUTTON,
    ON_CLICK_ABILITY_BUTTON,
    ON_CLICK_EQUIP_BUTTON,
    ON_CLICK_SETTING_BUTTON,
}


