
public enum EVENT_PLAYER
{
    PLAYER_LEFT_MOVE,
    PLAYER_RIGHT_MOVE,
    PLAYER_UP_MOVE,
    PLAYER_DOWN_MOVE,
    PLAYER_MOVE_COMPLETE,
    PLAYER_ATTACK_COMPLETE,
    PLAYER_DIE_COMPLETE,
    PLAYER_GET_ITEM_COMPLETE,
    PLAYER_EQUIP_INVENTORY_UPDATED,
}

public enum EVENT_ABILITY_INVEN_UI
{
    OPEN_ABILITY_DETAIL_UI,
    USE_ABILITY,
    SET_ABILITY,
}

public enum EVENT_EQUIP_INVEN_UI
{
    OPEN_EQUIP_INVENTORY_DETAIL_UI,

}

public enum EVENT_BOTTOM_BASE_UI
{
    ON_CLICK_DIR_BUTTON,
    ON_CLICK_CONSUME_BUTTON,
    ON_CLICK_ABILITY_BUTTON,
    ON_CLICK_EQUIP_BUTTON,
    ON_CLICK_SETTING_BUTTON,
}


